### ISSUE TITLE
Error "Blocked loading mixed active content" in FF

### ISSUE THREAD

**Issue by onox** [fgx/fgx-globe#2]
If https://fgx.github.io/fgx-globe/fgx-globe-r6/fgx-globe-r6-1.html is accessed, Firefox will block http:// requests.

**Comment by geoffmcl** [comment]
@onox that's interesting... I too get nothing if I use `https`, but remove the `s` and it works fine...

In firefox (Ubuntu 14.04 LTS, firefox 44.0.2) I get full screen flickering on each update...

In chrome (Win 7, chrome 48.0.2564.109 m) it works fine..

Thanks Theo, for an **interesting** world view, as usual...

**Comment by theo-armour** [comment]
Hi @onox

Thanks for looking into this

the script obtain's its data from Pete's server at:

http://crossfeed.freeflightsim.org/flights.json

The server only supports http therefore FGX Globe has to be http only.

In any case there is no important or private data being passed around so
data encryption is not a high priority in this case.

BTW, I noticed you flying overhead earlier today (I live in downtown San
Francisco ;-).

Any other thoughts?

Theo

**Comment by onox** [comment]
FF doesn't complain about the json request, only about the urls in the `<script>` tags.
